language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
os: 
  - "osx"
  - "linux"
  - "windows"
  - "freebsd"
jobs:
  allow_failures:
  - os:
    - "windows"
    - "freebsd"
  - node_js:
    - "11"
cache:
  yarn: true
