language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "14"
  - "15"
os: 
  - "osx"
  - "linux"
  - "windows"
  - "freebsd"
jobs:
  allow_failures:
    - os: 
      - "windows"
    - node_js:
      - 11
    - os: 
      - "freebsd"
cache:
  yarn: true
