name: Testing

on:
  push:
    branches:
      - master
    paths:
      - '**.ts'
  pull_request:
    branches: [master]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing with Node 20
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npm test
